esphome:
  name: "camera-${mac}"
  friendly_name: "Camera ${mac}"
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

api:
  encryption:
    key: ${api_key}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Camera ${mac} Fallback Hotspot"
    password: ${ap_pwd}

ota:
  - platform: esphome
    password: ${ota_pwd}


captive_portal:

psram:

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  # Image settings
  name: Live
  vertical_flip: False
  horizontal_mirror: False
  pixel_format: JPEG
  max_framerate: 24 fps
  resolution: 640X480
  frame_buffer_count: 2
    
    